version: '3.8'

services:
  teleport-service:
    build: .
    ports:
      - "8080:8080"
    container_name: teleport
    restart: always
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.50'